# Generated by Django 2.0.7 on 2018-08-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=4),
            preserve_default=False,
        ),
    ]
