# Generated by Django 2.0.7 on 2018-08-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20180809_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='like',
            name='timestamp',
        ),
    ]
