# Generated by Django 2.0.7 on 2018-08-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='kind',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sub',
            name='kind',
            field=models.CharField(max_length=32),
        ),
    ]
