# Generated by Django 2.0.7 on 2018-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180801_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='pizza_toppings',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='sub_toppings',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
