# Generated by Django 2.0.7 on 2018-08-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180801_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Item_Pizza_Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_id', models.IntegerField()),
                ('pizza_topping_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item_Sub_Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_id', models.IntegerField()),
                ('sub_topping_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='pizza_toppings',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='sub_toppings',
        ),
    ]
