# Generated by Django 2.0.7 on 2018-08-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180801_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item_Pizza_Toppings',
            new_name='Cart_Item_Pizza_Topping',
        ),
        migrations.RenameModel(
            old_name='Cart_Item_Sub_Toppings',
            new_name='Cart_Item_Sub_Topping',
        ),
    ]
