# Generated by Django 2.0.7 on 2018-08-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180802_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='cost',
            new_name='cost_s',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='cost',
            new_name='cost_s',
        ),
        migrations.AddField(
            model_name='pizza',
            name='cost_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='cost_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
