# Generated by Django 2.0.7 on 2018-08-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180802_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='cost_s',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='cost_s',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='cost_l',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='cost_l',
        ),
    ]
