# Generated by Django 2.0.7 on 2018-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180802_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Kind_Enum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
            ],
        ),
    ]
