# Generated by Django 2.0.7 on 2018-08-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dinner_platter_kind_enum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userId',
        ),
    ]
